### ISSUE TITLE
YeAudio是不支持python3.7吗

### ISSUE THREAD

**Issue by lsx193201** [yeyupiaoling/YeAudio#1]
我的python版本是3.7，按照安装步骤安装YeAudio，运行返回：
<img width="960" alt="image" src="https://github.com/user-attachments/assets/878a2a25-6a3a-43de-9c48-243fe7c85fe7">
用3.11的python版本安装却不会出错。

**Comment by yeyupiaoling** [comment]
不是的，是其中的一个依赖库scipy没有这个版本。

**Comment by lsx193201** [comment]
它规定scipy>=1.13.0，可是SciPy 1.13.0 版本需要 Python 3.8 或更高版本，那python3.7的环境不就无法安装YeAudio了吗

**Comment by yeyupiaoling** [comment]
那可以把这个版本设低一些。可以在依赖库列表里面修改。或者你安装的时候直接忽略依赖库。

**Comment by lsx193201** [comment]
已成功在python3.7的环境中安装YeAudio，万分感谢你的回复！
